### ISSUE TITLE
fresh install error

### ISSUE THREAD

**Issue by Owned67** [lilciv/Grafana-InfluxDB-Script#1]
`[Tue 09 Apr 2024 03:52:00 PM CEST] Your cert is in: /root/.acme.sh/grafana.mydomain.eu_ecc/grafana.mydomain.eu.cer
[Tue 09 Apr 2024 03:52:00 PM CEST] Your cert key is in: /root/.acme.sh/grafana.mydomain.eu_ecc/grafana.mydomain.eu.key
[Tue 09 Apr 2024 03:52:00 PM CEST] The intermediate CA cert is in: /root/.acme.sh/grafana.mydomain.eu_ecc/ca.cer
[Tue 09 Apr 2024 03:52:00 PM CEST] And the full chain certs is there: /root/.acme.sh/grafana.mydomain.eu_ecc/fullchain.cer
[Tue 09 Apr 2024 03:52:00 PM CEST] Installing key to: /etc/letsencrypt/live/grafana.mydomain.eu/privkey.pem
[Tue 09 Apr 2024 03:52:00 PM CEST] Installing full chain to: /etc/letsencrypt/live/grafana.mydomain.eu/fullchain.pem
[Tue 09 Apr 2024 03:52:00 PM CEST] Run reload cmd: docker restart InfluxDB && docker restart Grafana
Error response from daemon: No such container: InfluxDB
[Tue 09 Apr 2024 03:52:00 PM CEST] Reload error for :

Did your certificate obtain correctly? (You can ignore the reload error) [y,n]
`

Ive set yes, installation completed 

influxdb.mydomain.eu return 404...

thanks for any suggestion

**Comment by lilciv** [comment]
This all sounds like expected behavior. The reload error shows because the containers don't exist at the time the certificate is obtained. This can be ignored and will function as expected once the containers are spun up.
InfluxDB returns a 404 by default when you visit the base URL in a web browser. I am not seeing any issues with what you described here.

**Comment by Owned67** [comment]
ok thanks.
